import React, { useState } from 'react';
import { ArrowRight, BarChart3, ChevronDown, Clock3, TrendingDown, TrendingUp, UsersRound } from 'lucide-react';
import './analytics.css';

const strategies = [
  { name: 'FCFS', avg: '18.6 min', critical: '13.4 min', max: '48 min', util: '69%', throughput: '18.2', tone: 'neutral' },
  { name: 'Urgency Only', avg: '15.1 min', critical: '5.8 min', max: '61 min', util: '72%', throughput: '19.6', tone: 'blue' },
  { name: 'Urgency + Waiting', avg: '12.4 min', critical: '6.4 min', max: '29 min', util: '76%', throughput: '21.3', tone: 'best' },
  { name: 'Shortest Processing Time', avg: '13.9 min', critical: '11.2 min', max: '44 min', util: '74%', throughput: '20.1', tone: 'neutral' }
];

export default function Analytics() {
  const [tab, setTab] = useState('overview');
  return <div className="analytics-page">
    <section className="analytics-intro"><div><p className="eyebrow">SIMULATION PERFORMANCE</p><h2>Operational analytics</h2><p>Session-level performance across patient flow, resource utilization, and scheduling outcomes.</p></div><div className="analytics-filters"><Select value="Full session" values={['Full session', 'Last 5 min', 'Last 15 min']}/><Select value="All departments" values={['All departments', 'Emergency', 'Cardiology', 'Orthopedics']}/></div></section>
    <div className="analytics-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Performance overview</button><button className={tab === 'comparison' ? 'active' : ''} onClick={() => setTab('comparison')}>Strategy comparison <span>Bonus</span></button></div>
    {tab === 'overview' ? <Overview setTab={setTab}/> : <Comparison/>}
  </div>;
}
function Select({ value, values }) { return <label className="analytics-select"><select defaultValue={value}>{values.map(v => <option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label>; }
function Overview({ setTab }) { return <>
  <section className="analytics-kpis"><Metric value="142" label="Patients processed" note="+18 in last hour"/><Metric value="118" label="Patients completed" note="83% completion rate"/><Metric value="24" label="Currently waiting" note="Peak: 31 patients"/><Metric value="14 min" label="Average wait" note="↓ 3 min vs. start" positive/><Metric value="31 min" label="Maximum wait" note="Target: under 35 min"/><Metric value="7.1 min" label="Critical-patient wait" note="Priority metric" blue/><Metric value="21.3" label="Throughput" note="Patients per hour" positive/></section>
  <section className="analytics-grid">
    <ChartCard title="Patient flow" eyebrow="SIMULATION RUN" className="flow-card"><div className="flow-legend"><span><i className="arrivals"/>Arrivals</span><span><i className="assessment"/>Assessment</span><span><i className="consult"/>Consultation</span><span><i className="complete"/>Completed</span></div><div className="flow-chart"><div className="chart-lines"><i/><i/><i/></div><svg viewBox="0 0 500 145" preserveAspectRatio="none"><path d="M0,115 C35,105 48,72 80,86 S130,40 162,72 S210,55 245,63 S285,23 322,51 S375,25 415,44 S464,23 500,29 L500,145 L0,145Z" fill="#d0e2ff"/><path d="M0,121 C36,111 45,94 80,101 S133,63 162,84 S210,74 245,77 S286,46 322,64 S375,41 415,57 S461,37 500,42" fill="none" stroke="#0f62fe" strokeWidth="3"/><path d="M0,131 C46,128 63,115 100,120 S154,95 187,106 S245,93 273,97 S326,73 355,84 S416,62 455,70 S485,57 500,61" fill="none" stroke="#198038" strokeWidth="3"/></svg><div className="chart-axis"><span>10:00</span><span>10:15</span><span>10:30</span><span>10:45</span><span>11:00</span></div></div></ChartCard>
    <ChartCard title="Queue length" eyebrow="LIVE LOAD"><div className="queue-chart"><div className="chart-lines"><i/><i/><i/></div><svg viewBox="0 0 400 145" preserveAspectRatio="none"><path d="M0,105 C32,96 52,73 73,84 S125,102 146,83 S195,45 221,68 S275,44 307,60 S358,25 400,38" fill="none" stroke="#0f62fe" strokeWidth="3"/><path d="M0,105 C32,96 52,73 73,84 S125,102 146,83 S195,45 221,68 S275,44 307,60 S358,25 400,38 L400,145 L0,145Z" fill="#e8f1ff" opacity=".65"/></svg><div className="chart-axis"><span>10:00</span><span>10:20</span><span>10:40</span><span>11:00</span></div></div><div className="chart-callout"><TrendingUp size={16}/><span>Peak queue length: <b>31 patients</b> during surge period</span></div></ChartCard>
    <ChartCard title="Average waiting time" eyebrow="PERFORMANCE"><div className="line-summary"><b>14 min</b><span><TrendingDown size={14}/> 18% lower than session start</span></div><div className="queue-chart small"><div className="chart-lines"><i/><i/><i/></div><svg viewBox="0 0 400 100" preserveAspectRatio="none"><path d="M0,35 C30,38 51,45 78,40 S124,62 150,56 S199,71 222,65 S275,82 300,74 S350,93 400,82" fill="none" stroke="#198038" strokeWidth="3"/></svg></div></ChartCard>
    <ChartCard title="Patients by department" eyebrow="VOLUME"><Bar label="Emergency" value={88} count="46"/><Bar label="Cardiology" value={65} count="34"/><Bar label="General Medicine" value={74} count="39"/><Bar label="Orthopedics" value={44} count="23"/></ChartCard>
  </section>
  <section className="analytics-grid lower-analytics"><ChartCard title="Department performance" eyebrow="CURRENT SESSION" className="performance-table"><table><thead><tr><th>DEPARTMENT</th><th>VOLUME</th><th>AVG. WAIT</th><th>COMPLETED</th><th>IN QUEUE</th></tr></thead><tbody>{[['Emergency','46','17 min','37','9'],['Cardiology','34','12 min','29','5'],['General Medicine','39','14 min','32','7'],['Orthopedics','23','8 min','20','3']].map(r => <tr key={r[0]}>{r.map(c => <td key={c}>{c}</td>)}</tr>)}</tbody></table></ChartCard><ChartCard title="Resource utilization" eyebrow="CAPACITY"><Util label="Doctors" value={75}/><Util label="General beds" value={75}/><Util label="ICU beds" value={92} alert/><Util label="Operating rooms" value={67}/></ChartCard></section>
  <section className="compare-prompt"><div><BarChart3 size={23}/><div><p className="eyebrow">SCHEDULING INSIGHT</p><h2>How does the current strategy compare?</h2><span>Run the same arrivals against each strategy to evaluate wait time, equity, and resource utilization.</span></div></div><button onClick={() => setTab('comparison')}>Compare strategies <ArrowRight size={17}/></button></section>
</>; }
function Comparison() { return <>
  <section className="comparison-hero"><div><p className="eyebrow">LIKE-FOR-LIKE SIMULATION</p><h2>Scheduling strategy comparison</h2><p>All strategies use the same patient arrival stream and resource conditions.</p></div><div className="compare-chip">Random seed: 2048 · 142 patients</div></section>
  <section className="strategy-table panel"><table><thead><tr><th>METRIC</th>{strategies.map(s => <th key={s.name} className={s.tone === 'best' ? 'recommended' : ''}>{s.name}{s.tone === 'best' && <span className="recommend">Recommended</span>}</th>)}</tr></thead><tbody>{[['Average wait','avg'],['Critical-patient average wait','critical'],['Maximum wait','max'],['Resource utilization','util'],['Throughput (patients/hour)','throughput']].map(([label,key]) => <tr key={key}><td><b>{label}</b></td>{strategies.map(s => <td key={s.name} className={s.tone === 'best' ? 'recommended' : ''}>{s[key]}</td>)}</tr>)}</tbody></table></section>
  <div className="comparison-grid"><ChartCard title="Wait time by urgency level" eyebrow="LOWER IS BETTER" className="urgency-chart"><div className="grouped-bars">{[['Urgent',[8,4,5,10]],['High',[14,10,9,11]],['Moderate',[21,19,14,13]],['Stable',[31,42,20,18]]].map(([label, vals]) => <div className="bar-group" key={label}><span>{label}</span><div>{vals.map((value,i) => <i key={i} className={`strat-${i}`} style={{height:`${value*2}px`}} title={`${value} min`}/>)}</div></div>)}</div><div className="strategy-legend"><span><i className="strat-0"/>FCFS</span><span><i className="strat-1"/>Urgency Only</span><span><i className="strat-2"/>Urgency + Waiting</span><span><i className="strat-3"/>Shortest Processing</span></div></ChartCard><section className="panel insight-card"><p className="eyebrow">KEY FINDING</p><h2>Aging prevents low-priority starvation.</h2><p>Urgency-only scheduling delivers the fastest urgent care, but gives stable patients the longest wait. Adding waiting-time aging keeps critical care fast while reducing maximum wait by <b>52%</b>.</p><div><span>Urgency + Waiting</span><b>Best balanced outcome</b></div><button>Apply Urgency + Waiting <ArrowRight size={16}/></button></section></div>
  <section className="strategy-notes"><div><h3>FCFS</h3><p>Fair arrival order, but misses clinical urgency.</p></div><div><h3>Urgency Only</h3><p>Fastest critical response; risks starving stable patients.</p></div><div className="best-note"><h3>Urgency + Waiting</h3><p>Balances clinical urgency with queue aging.</p></div><div><h3>Shortest Processing</h3><p>Strong throughput; may delay complex critical care.</p></div></section>
</>; }
function Metric({ value, label, note, positive, blue }) { return <div className={`metric ${blue ? 'blue' : ''}`}><b>{value}</b><span>{label}</span><small className={positive ? 'positive' : ''}>{note}</small></div>; }
function ChartCard({ title, eyebrow, children, className = '' }) { return <section className={`chart-card panel ${className}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>; }
function Bar({ label, value, count }) { return <div className="bar-row"><span>{label}</span><i><em style={{width:`${value}%`}}/></i><b>{count}</b></div>; }
function Util({ label, value, alert }) { return <div className="analytics-util"><div><span>{label}</span><b>{value}%</b></div><i><em className={alert ? 'alert' : ''} style={{width:`${value}%`}}/></i></div>; }
